#!/bin/sh

# $HOME/.i3/conky

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1, "click_events": true}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:
exec conky -c ~/.i3/conkyrc
